name = "meyou-blue"
main = "worker.js"
compatibility_date = "2024-11-01"

[[r2_buckets]]
binding = "SITE"
bucket_name = "mb-site-workspace"

[vars]
ALLOW_ORIGINS = '["https://mb.meyoustudios.com","https://<your>.pages.dev"]'
